"""core.live_edit.apply — apply a PatchSpec, write the overlay file, reload.

The overlay is a small module that imports the original runner, defines a
subclass that overrides only the target method, and exposes the subclass as
`LiveRunner`. Reloading the runner module and rebinding `Runner` to the
subclass is the orchestrator's job (via `reload_runner_with_overlays`).

A revert deletes the overlay file and reloads the original.
"""
from __future__ import annotations

import ast
import dataclasses
import importlib
import os
import sys
import time
from pathlib import Path
from typing import Any, Callable, Optional

from .patch import (
    PatchSpec,
    resolve_patch,
    validate_patch,
)
from .log import _OVERLAY_LOG, _LOG_PATH, _append_log


_OVERLAY_ROOT = Path(__file__).parent / "overlays"


def _module_name_to_overlay_path(runner_module_name: str, ts: float) -> Path:
    """Map `core.wifi_attack.runner` → `core/live_edit/overlays/core.wifi_attack.runner/__live_<ts>.py`."""
    safe = runner_module_name.replace(".", "_")
    target_dir = _OVERLAY_ROOT / safe
    target_dir.mkdir(parents=True, exist_ok=True)
    return target_dir / f"__live_{int(ts * 1000)}.py"


def _emit_overlay_source(
    runner_module_name: str,
    runner_class_name: str,
    method_name: str,
    new_method_node: ast.FunctionDef,
) -> str:
    """Return the source of an overlay module that subclasses the original
    runner and overrides `method_name` with the patched AST.

    The overlay is the only thing written; importlib loads it and the new
    class shadows the original via `reload_runner_with_overlays`.
    """
    import textwrap as _textwrap
    method_src = ast.unparse(new_method_node)
    # The class body lives inside a 4-space indent. ast.unparse() returns
    # the def at column 0 and the body at column 4; we need the def at
    # column 4 and the body at column 8. Re-indent every line by 4.
    # NOTE: don't put {method_src} on its own line in a triple-quoted
    # f-string — Python's f-string dedent logic strips the extra leading
    # whitespace from continuation lines, so the body lands at the same
    # column as the def. Concatenation avoids that pitfall.
    method_src = _textwrap.indent(method_src, prefix="    ")
    ts_str = f"{time.time():.0f}"
    return (
        f'"""Auto-generated overlay — DO NOT EDIT BY HAND.\n'
        f"\n"
        f"Generated by core.live_edit.apply_patch at {ts_str}.\n"
        f"Original module: {runner_module_name}\n"
        f"Original class:  {runner_class_name}\n"
        f"Patched method:  {method_name}\n"
        f'"""\n'
        f"from __future__ import annotations\n"
        f"import importlib\n"
        f"import {runner_module_name} as _orig\n"
        f"\n"
        f"_Runner = getattr(_orig, {runner_class_name!r}, None)\n"
        f"if _Runner is None:\n"
        f"    # last-ditch: try to import the class from the module\n"
        f"    _Runner = importlib.import_module({runner_module_name!r}).__dict__.get({runner_class_name!r})\n"
        f"\n"
        f"\n"
        f"class LiveOverlay{runner_class_name}(_Runner):\n"
        f"{method_src}\n"
        f"\n"
        f"\n"
        f"def _get_runner():\n"
        f"    return LiveOverlay{runner_class_name}\n"
        f"\n"
        f"\n"
        f'__all__ = ["LiveOverlay{runner_class_name}", "_get_runner"]\n'
    )


def apply_patch(
    spec: PatchSpec,
    *,
    confirm_fn: Optional[Callable[[str], bool]] = None,
) -> Optional[str]:
    """Apply a PatchSpec.

    Steps:
        1. Resolve the safe-patch by id
        2. Parse the runner module's source, locate the target class
        3. Locate the `_method` AST node
        4. Run the patch transform to produce a new method node
        5. validate_patch() on the new node
        6. confirm_fn() (the operator's gate) — must accept the patch
        7. Write the overlay module
        8. Log the patch
        9. Return the overlay module path (None on refusal)

    Args:
        spec:        the patch request
        confirm_fn:  a callable that takes a description and returns bool.
                     If None, the patch is applied (caller is responsible
                     for having gated the decision elsewhere — the runner's
                     per-step gate fires on the OUTER step, not on the
                     inner patch).

    Returns:
        The path to the overlay module on success, None on refusal.
    """
    fn = resolve_patch(spec.patch_id)
    if fn is None:
        _append_log({
            "event": "refuse",
            "reason": f"unknown patch_id {spec.patch_id!r}",
            "spec": dataclasses.asdict(spec),
        })
        return None

    # locate the runner module
    try:
        runner_module = importlib.import_module(spec.target_runner)
    except ImportError as e:
        _append_log({
            "event": "refuse",
            "reason": f"import error: {e}",
            "spec": dataclasses.asdict(spec),
        })
        return None

    # parse the source
    try:
        src_path = Path(runner_module.__file__)
        if src_path.suffix != ".py":
            return None
        source = src_path.read_text()
        tree = ast.parse(source, filename=str(src_path))
    except (OSError, SyntaxError) as e:
        _append_log({
            "event": "refuse",
            "reason": f"parse error: {e}",
            "spec": dataclasses.asdict(spec),
        })
        return None

    # locate the class — there may be several; take the first that has
    # a method matching target_method
    runner_class: Optional[type] = None
    runner_class_node: Optional[ast.ClassDef] = None
    method_node: Optional[ast.FunctionDef] = None
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            for item in node.body:
                if isinstance(item, ast.FunctionDef) and item.name == spec.target_method:
                    runner_class = getattr(runner_module, node.name, None)
                    runner_class_node = node
                    method_node = item
                    break
            if method_node is not None:
                break

    if method_node is None or runner_class is None or runner_class_node is None:
        _append_log({
            "event": "refuse",
            "reason": f"method {spec.target_method!r} not found on any class in {spec.target_runner!r}",
            "spec": dataclasses.asdict(spec),
        })
        return None

    # run the transform
    try:
        new_method = fn(method_node, **spec.params)
    except Exception as e:
        _append_log({
            "event": "refuse",
            "reason": f"transform raised: {e!r}",
            "spec": dataclasses.asdict(spec),
        })
        return None

    if not isinstance(new_method, ast.FunctionDef):
        _append_log({
            "event": "refuse",
            "reason": f"transform did not return a FunctionDef",
            "spec": dataclasses.asdict(spec),
        })
        return None

    # validate
    ok, reason = validate_patch(spec, new_method, pre_node=method_node)
    if not ok:
        _append_log({
            "event": "refuse",
            "reason": f"validation failed: {reason}",
            "spec": dataclasses.asdict(spec),
        })
        return None

    # gate
    if confirm_fn is not None:
        gate_msg = (
            f"AI proposes live-edit patch {spec.patch_id!r} on "
            f"{spec.target_runner}.{runner_class_node.name}.{spec.target_method}: "
            f"{spec.rationale!r}"
        )
        if not confirm_fn(gate_msg):
            _append_log({
                "event": "refuse",
                "reason": "operator CANCELLED the patch",
                "spec": dataclasses.asdict(spec),
            })
            return None

    # write the overlay
    overlay_path = _module_name_to_overlay_path(spec.target_runner, time.time())
    overlay_src = _emit_overlay_source(
        runner_module_name=spec.target_runner,
        runner_class_name=runner_class_node.name,
        method_name=spec.target_method,
        new_method_node=new_method,
    )
    overlay_path.write_text(overlay_src)

    _append_log({
        "event": "apply",
        "overlay": str(overlay_path),
        "spec": dataclasses.asdict(spec),
    })
    return str(overlay_path)


def revert_patch(overlay_path: str) -> bool:
    """Delete an overlay file. Returns True on success, False on error.

    After reverting, the caller should `reload_runner_with_overlays` to
    re-import the original runner module.
    """
    p = Path(overlay_path)
    if not p.exists():
        _append_log({"event": "revert_fail", "reason": "missing", "path": overlay_path})
        return False
    try:
        p.unlink()
        _append_log({"event": "revert", "path": overlay_path})
        return True
    except OSError as e:
        _append_log({"event": "revert_fail", "reason": str(e), "path": overlay_path})
        return False
