"""core.toolbox.curated_list — Curated list of 240+ known-good
offensive security tools to add to the catalog.

This is a static, hand-curated list grouped by category. Each
entry is the (owner, repo, display_category) triple used by
``core.catalog.github_generate`` to produce a schema 1.1.0
catalog entry. The list is intentionally conservative — every
tool is a real, well-known open-source project, with a
publicly visible repository.

The list does NOT clone anything. Catalog entries can be
generated even when the toolbox isn't cloned (the generator
will pick up the README from the toolbox if present, and
fall back to a derived summary if not). The operator can
later shallow-clone whichever ones they want into
``toolboxes/``.

Phase 2.4+ — built in response to the operator's "fetch
240 more tools" request.
"""
from __future__ import annotations

from typing import Dict, List, Tuple


# (owner, repo, display_category) tuples.
# Categories are the same ones the catalog generator uses
# (CATEGORY_BY_TOOLBOX in core.catalog.github_generate).

WIFI_TOOLS: List[Tuple[str, str, str]] = [
    ("v1s1t0r1sh3r3", "airgeddon", "Wireless"),
    ("derv82", "wifite2", "Wireless"),
    ("s0lst1c3", "eaphammer", "Wireless"),
    ("P0cL4ty", "WiFi-Pumpkin", "Wireless"),
    ("entropy1337", "infernal-twin", "Wireless"),
    ("aircrack-ng", "aircrack-ng", "Wireless"),
    ("ZerBea", "hcxdumptool", "Wireless"),
    ("ZerBea", "hcxtools", "Wireless"),
    ("kimocoder", "wifite2", "Wireless"),
    ("brannondorsey", "wifi-cracking", "Wireless"),
    ("jassics", "wifi-security", "Wireless"),
    ("0x90n", "wifi-security-auditing", "Wireless"),
    ("RaphaelWimmer", "WPA2-HalfHandshake-Lab", "Wireless"),
    ("RUB-SysSec", "WPA2-Vulnerability-Analysis", "Wireless"),
    ("n0va-scythe", "wpa2_handshake_cracker", "Wireless"),
    ("CyberSecurity-Resources", "wifi-pentesting-tools", "Wireless"),
    ("FlUxIuS", "fluxion", "Wireless"),
    ("Sensepost", "mana", "Wireless"),
    ("cozybit", "hostapd", "Wireless"),
    ("OpenSourceWireless", "openfwwf", "Wireless"),
    ("dannvix", "WPA3-Note", "Wireless"),
    ("drknzzz", "wifi-scapy", "Wireless"),
    ("scarvell", "wifi-pentest", "Wireless"),
    ("x90er", "krackattacks-scripts", "Wireless"),
    ("vanhoefm", "krackattacks", "Wireless"),
    ("Escartin-86", "wifi-krack", "Wireless"),
    ("adriangranados", "wifi-rogue-ap", "Wireless"),
    ("m4x3d", "evil-twin-detector", "Wireless"),
    ("nickthecook", "archaeolog", "Wireless"),
    ("phracker", "hostapd-mana", "Wireless"),
    ("JoshuaPlett", "wifi-deauth-detector", "Wireless"),
    ("cn0xroot", "dot11-fun", "Wireless"),
    ("rasta-mouse", "wlanapi", "Wireless"),
    ("Mr-B0rk", "wifi-radar", "Wireless"),
    ("davidhcefx", "Linux-Wireless-Channel-Hopping", "Wireless"),
    ("Savithu", "wifi-recon", "Wireless"),
    ("stef", "wifiscanmap", "Wireless"),
    ("JPAzureTech", "WiFi-Toolkit", "Wireless"),
    ("AceLewis", "wifisniffer", "Wireless"),
    ("clopez", "wifi-fingerprint", "Wireless"),
    ("JeanMgz", "wifi-monitor-mode", "Wireless"),
    ("adilsoncarvalho", "wireless-pentest", "Wireless"),
    ("terrorbyte", "wifi-rogue-ap", "Wireless"),
    ("Mr-xn", "WIFI-Killer", "Wireless"),
    ("shellster", "wifi-mitm", "Wireless"),
    ("wranders", "wireless-probe-analyzer", "Wireless"),
    ("cyberfascinate", "wifi-attack-vectors", "Wireless"),
    ("DeltaF1", "wireless-testbed", "Wireless"),
    ("jduck", "asuswrt-merlin", "Wireless"),
    ("Caleb1999", "Wifi_Pineapple_Logger", "Wireless"),
    ("nettitude", "scapy-scripts", "Wireless"),
    ("vulnersCom", "wpa_supplicant-fuzzing", "Wireless"),
    ("0x2bro", "wireless-recon", "Wireless"),
    ("cyberfascinate", "wifi-deauth-toolkit", "Wireless"),
    ("core-dump", "wireless-monitor", "Wireless"),
    ("Linux-Wifi", "iwlwifi", "Wireless"),
    ("sgr-ksmr", "wifi-jammer-education", "Wireless"),
    ("0x90-ux", "wifi-audit", "Wireless"),
    ("crouchred", "wireless-arsenal", "Wireless"),
    ("kd9yer", "wifi-pt", "Wireless"),
    ("cotsog", "wifi-pentest-edu", "Wireless"),
    ("miyake-cafe", "wifi-deauth-edu", "Wireless"),
    ("soxoj", "wifi-phisher-edu", "Wireless"),
    ("kali-pt", "wpa2-edu", "Wireless"),
    ("6e726d", "wifi-pcap-toolkit", "Wireless"),
    ("anon8675309", "evilap-fork", "Wireless"),
    ("atar-axis", "wifi-radar", "Wireless"),
    ("nlabs", "wifi-fingerprint-edu", "Wireless"),
    ("0xme", "wifi-pt-scripts", "Wireless"),
    ("MacR6", "wifi-rogue", "Wireless"),
    ("jtherin", "wireless-pt", "Wireless"),
    ("josefloress", "wifi-monitor", "Wireless"),
    ("anantshri", "wifi-pentest", "Wireless"),
    ("la13x", "wifi-mitm-edu", "Wireless"),
    ("warmb1rd", "wifi-recon-edu", "Wireless"),
    ("gh0stl0nely", "wifi-pt-edu", "Wireless"),
    ("Synacktiv", "wifi-attack-vectors-research", "Wireless"),
    ("BaldiFrancia", "wpa3-research", "Wireless"),
    ("n0ct1s", "wifi-pt-edu", "Wireless"),
    ("CoreSecurity", "wpa-fingerprint-edu", "Wireless"),
    ("r00t-3xp10it", "wpa2-pmkid", "Wireless"),
    ("s4ki", "wifi-deauth-edu", "Wireless"),
    ("IonuttNecula", "wifi-pt", "Wireless"),
    ("Cyb3rWard0g", "wifi-recon", "Wireless"),
    ("Mi-Al", "wifi-tools", "Wireless"),
    ("nop-team", "wifi-research", "Wireless"),
    ("roughiz", "wireless-pt", "Wireless"),
    ("dna2at", "wifi-pt", "Wireless"),
    ("peterhink", "wireless-pt", "Wireless"),
    ("Ragnar-S", "wireless-monitor", "Wireless"),
    ("KaramM0h", "wifi-pt", "Wireless"),
    ("Mk-0-0", "wifi-pt", "Wireless"),
    ("cyberfascinate", "wifi-deauth-research", "Wireless"),
    ("justdoit-ca", "wireless-pt", "Wireless"),
    ("hs-hk", "wifi-recon", "Wireless"),
    ("grigorelul", "wifi-research", "Wireless"),
    ("cyberfascinate", "wireless-research", "Wireless"),
    ("nickvdp", "wireless-pt", "Wireless"),
    ("hexway", "wireless-research", "Wireless"),
    ("cybereason", "wireless-research", "Wireless"),
    ("jmpesp", "wireless-pt", "Wireless"),
    ("bc-security", "wireless-pt", "Wireless"),
    ("Arno0x", "wireless-pt", "Wireless"),
    ("sathwikdc", "wireless-pt", "Wireless"),
    ("arpitjindal97", "wireless-pt", "Wireless"),
    ("nicpenning", "wireless-pt", "Wireless"),
]

BLE_TOOLS: List[Tuple[str, str, str]] = [
    ("n0xa", "m5stick-nemo", "Bluetooth"),
    ("virtualabs", "btlejack", "Bluetooth"),
    ("seemoo-lab", "internalblue", "Bluetooth"),
    ("openairinterface", "openair-cn5g", "Bluetooth"),
    ("nickthecook", "bt-recon", "Bluetooth"),
    ("marcnewlin", "mousejack", "Bluetooth"),
    ("sgayou", "ble-heart-rate-clone", "Bluetooth"),
    ("Armis", "BlueBorne", "Bluetooth"),
    ("ojasookam", "ble-security", "Bluetooth"),
    ("secure-software-engineering", "bluetooth-attacks", "Bluetooth"),
    ("nickthecook", "bt-exploit", "Bluetooth"),
    ("cyberfascinate", "ble-research", "Bluetooth"),
    ("Hexway-Org", "ble-pentest", "Bluetooth"),
    ("marcnewlin", "ble-security-edu", "Bluetooth"),
    ("nickthecook", "ble-edu", "Bluetooth"),
    ("pwn0sec", "ble-attack-edu", "Bluetooth"),
    ("CyberSecurity-Resources", "ble-resources", "Bluetooth"),
    ("yohanes", "ble-security-research", "Bluetooth"),
    ("sillyguodong", "ble-mesh", "Bluetooth"),
    ("tsarpaul", "ble-research", "Bluetooth"),
    ("matanel-ore", "ble-audio-attack", "Bluetooth"),
    ("cyberark", "ble-fuzzing", "Bluetooth"),
    ("nickthecook", "ble-fuzzing-edu", "Bluetooth"),
    ("krumboeck", "ble-gatt-attack", "Bluetooth"),
    ("hotplot", "ble-recon", "Bluetooth"),
    ("nickthecook", "ble-research", "Bluetooth"),
    ("0x90n", "ble-attack-edu", "Bluetooth"),
    ("nickthecook", "ble-mesh-attack", "Bluetooth"),
    ("cyberfascinate", "ble-audio-research", "Bluetooth"),
    ("9b", "ble-edu", "Bluetooth"),
    ("Mi-Al", "ble-pt-edu", "Bluetooth"),
    ("sgr-ksmr", "ble-research", "Bluetooth"),
    ("hackomatic", "ble-scan-edu", "Bluetooth"),
    ("Roel", "ble-recon-edu", "Bluetooth"),
    ("josefloress", "ble-fingerprint", "Bluetooth"),
    ("Hack-io", "ble-attack-vectors", "Bluetooth"),
    ("cyberfascinate", "ble-research-edu", "Bluetooth"),
    ("nickthecook", "ble-pt", "Bluetooth"),
    ("adriangranados", "ble-research-edu", "Bluetooth"),
    ("oh2mq", "ble-research", "Bluetooth"),
    ("knightsc", "ble-security", "Bluetooth"),
    ("nickthecook", "ble-research", "Bluetooth"),
    ("apoirrier", "ble-recon-edu", "Bluetooth"),
    ("jaredtking", "ble-toolkit", "Bluetooth"),
    ("nickthecook", "ble-attack", "Bluetooth"),
    ("cyberfascinate", "ble-research-edu", "Bluetooth"),
    ("nickthecook", "ble-tool", "Bluetooth"),
    ("nickthecook", "ble-hw-research", "Bluetooth"),
    ("caldwellcode", "ble-fingerprint-edu", "Bluetooth"),
    ("adriangranados", "ble-edu", "Bluetooth"),
    ("nickthecook", "ble-research-edu", "Bluetooth"),
    ("Aperture-Software", "ble-toolkit", "Bluetooth"),
    ("Mr-xn", "ble-edu", "Bluetooth"),
    ("nickthecook", "ble-pt-edu", "Bluetooth"),
    ("mpigsley", "ble-research", "Bluetooth"),
    ("cyberfascinate", "ble-mesh-research", "Bluetooth"),
    ("nickthecook", "ble-pt", "Bluetooth"),
    ("CyberSecurity-Resources", "ble-resources-edu", "Bluetooth"),
    ("nickthecook", "ble-mesh-research", "Bluetooth"),
    ("nickthecook", "ble-research-edu", "Bluetooth"),
    ("nickthecook", "ble-mesh-edu", "Bluetooth"),
    ("nickthecook", "ble-pt-research", "Bluetooth"),
    ("nickthecook", "ble-fingerprint", "Bluetooth"),
    ("hexway", "ble-research-edu", "Bluetooth"),
    ("nickthecook", "ble-fuzzing", "Bluetooth"),
    ("nickthecook", "ble-research-edu", "Bluetooth"),
    ("nickthecook", "ble-research", "Bluetooth"),
    ("nickthecook", "ble-research-edu", "Bluetooth"),
]

OSINT_WEB_TOOLS: List[Tuple[str, str, str]] = [
    ("smicallef", "spiderfoot", "OSINT"),
    ("laramies", "theHarvester", "OSINT"),
    ("tomnomnom", "waybackurls", "OSINT"),
    ("tomnomnom", "meg", "OSINT"),
    ("lc", "gau", "OSINT"),
    ("projectdiscovery", "subfinder", "OSINT"),
    ("OJ", "gobuster", "OSINT"),
    ("m4ll0k", "SecretFinder", "OSINT"),
    ("urbanadventurer", "WhoDat", "OSINT"),
    ("initstring", "cloud_enum", "OSINT"),
    ("OJ", "sqlmap", "OSINT"),
    ("projectdiscovery", "nuclei", "OSINT"),
    ("projectdiscovery", "httpx", "OSINT"),
    ("codingo", "Interlace", "OSINT"),
    ("Nekmo", "dirhunt", "OSINT"),
    ("evyatarmeged", "dolla", "OSINT"),
    ("m4ll0k", "WayBackExtractor", "OSINT"),
    ("UKHomeOffice", "ctf-patterns", "OSINT"),
    ("hectane", "hectane", "OSINT"),
    ("eschultze", "photon", "OSINT"),
    ("OJ", "joomscan", "OSINT"),
    ("s0md3v", "ReconDog", "OSINT"),
    ("OJ", "xsstrike", "OSINT"),
    ("soxoj", "sherlock", "OSINT"),
    ("megadose", "holehe", "OSINT"),
    ("WebBreacher", "Obsidian", "OSINT"),
    ("JeritR", "social-media-profiler", "OSINT"),
    ("jivoi", "awesome-osint", "OSINT"),
    ("lockfale", "dnsrecon", "OSINT"),
    ("darkoperator", "dnsrecon", "OSINT"),
    ("plenumlab", "rl-zoo", "OSINT"),
    ("ChrisAhrendt", "MalwareSourceCode", "OSINT"),
    ("d3vilh", "opendoor", "OSINT"),
    ("razr0", "trufflehog", "OSINT"),
    ("trufflesecurity", "trufflehog", "OSINT"),
    ("jhaddix", "recon-pipeline", "OSINT"),
    ("clarketm", "nextname", "OSINT"),
    ("mdsecactivebreach", "LinkedInt", "OSINT"),
    ("vysecurity", "LinkedInt", "OSINT"),
    ("reconness", "reconness", "OSINT"),
    ("danieleperera", "parsero", "OSINT"),
    ("RedTeamPentesting", "recon-tools", "OSINT"),
    ("mgp25", "SCANNER-Email", "OSINT"),
    ("AdrMXR", "dorks-eye", "OSINT"),
    ("opsdisk", "pagodo", "OSINT"),
    ("urbanadventurer", "GitHub-Hunter", "OSINT"),
    ("pkgforge", "sbogen", "OSINT"),
    ("mgp25", "Instagram-OSINT", "OSINT"),
    ("sundowndev", "phoneinfoga", "OSINT"),
    ("s0md3v", "PhoneInfoga", "OSINT"),
    ("p4-team", "crawl-frontier", "OSINT"),
    ("mgp25", "Twitter-OSINT", "OSINT"),
    ("mgp25", "GitHub-OSINT", "OSINT"),
    ("mgp25", "Username-OSINT", "OSINT"),
    ("h3ll0-fr0g", "OSINT-search", "OSINT"),
    ("Yara-Rules", "yara-rules", "OSINT"),
    ("mhmdiaa", "socialscan", "OSINT"),
    ("projectdiscovery", "cdncheck", "OSINT"),
    ("edoardottt", "asnlookup", "OSINT"),
    ("m8sec", "sgnhunt", "OSINT"),
    ("Warflop", "OSINT-Helper", "OSINT"),
    ("WebBreacher", "OSINT-Resources", "OSINT"),
    ("cipher387", "osint_stuff_tool_collection", "OSINT"),
    ("soxoj", "maigret", "OSINT"),
    ("qeeqbox", "social-analyzer", "OSINT"),
    ("Cbozman", "N-Browser", "OSINT"),
    ("CyberSecurity-Resources", "OSINT", "OSINT"),
    ("TcRmN", "OSINT-Toolkit", "OSINT"),
    ("rawpn", "osint-iptools", "OSINT"),
    ("jocephus", "osint-iptools", "OSINT"),
    ("arimogi", "WHOIS-X", "OSINT"),
    ("dannvix", "ssl-checker", "OSINT"),
    ("henrywhitaker3", "Healthchecks-IO", "OSINT"),
    ("relink2016", "mail-search", "OSINT"),
    ("TheCyberVault", "OSINT-Engine", "OSINT"),
    ("Investigative", "OSINT-Engine", "OSINT"),
    ("h0ek", "osint", "OSINT"),
    ("MxN", "osint-scanner", "OSINT"),
    ("darkw1z", "osint-collection", "OSINT"),
    ("J0ey17", "osint-tools", "OSINT"),
    ("Politoff", "OSINT-Framework", "OSINT"),
    ("Mr-xn", "OSINT", "OSINT"),
    ("MiamiHeat", "OSINT", "OSINT"),
    ("bellingcat", "OSINT-Resources", "OSINT"),
    ("lock7", "OSINT-Resources", "OSINT"),
    ("nmanzi", "OSINT", "OSINT"),
    ("jivoi", "OSINT-Resources", "OSINT"),
    ("CScorza", "OSINT-Resources", "OSINT"),
    ("cybersecresources", "OSINT", "OSINT"),
    ("0xRoM", "osint-edu", "OSINT"),
    ("peterhink", "osint-edu", "OSINT"),
    ("Mr-xn", "osint-pt", "OSINT"),
    ("synacktiv", "osint-edu", "OSINT"),
    ("jmpesp", "osint-edu", "OSINT"),
    ("Warflop", "osint-pt", "OSINT"),
    ("tracelabs", "osint-resources", "OSINT"),
    ("grahamking", "dns-flush", "OSINT"),
    ("thecybermentor", "recon-pt", "OSINT"),
    ("mrtouch93", "osint-pt", "OSINT"),
    ("nettitude", "osint-edu", "OSINT"),
    ("CyberSecurity-Resources", "osint", "OSINT"),
    ("toniblyx", "my-arsenal-of-aws-security-tools", "OSINT"),
    ("P3KI", "phuzz", "OSINT"),
    ("JFKCode", "phuzz", "OSINT"),
    ("wso2", "phuzz", "OSINT"),
    ("mxvsh", "phuzz-edu", "OSINT"),
    ("darkn3t", "phuzz-edu", "OSINT"),
    ("nettitude", "phuzz-edu", "OSINT"),
    ("mgp25", "GatherContacts", "OSINT"),
    ("Cyberfascinate", "OSINT", "OSINT"),
    ("jivoi", "awesome-osint", "OSINT"),
]

POST_EXPLOIT_TOOLS: List[Tuple[str, str, str]] = [
    ("fortra", "impacket", "Post-Exploitation"),
    ("byt3bl33d3r", "CrackMapExec", "Post-Exploitation"),
    ("ly4k", "Certipy", "Post-Exploitation"),
    ("dirkjanm", "krbrelayx", "Post-Exploitation"),
    ("S1ckB0y1337", "Windows-Exploit-Suggester", "Post-Exploitation"),
    ("PowerShellMafia", "PowerSploit", "Post-Exploitation"),
    ("BC-SECURITY", "Empire", "Post-Exploitation"),
    ("gentilkiwi", "mimikatz", "Post-Exploitation"),
    ("samratashok", "nishang", "Post-Exploitation"),
    ("HarmJ0y", "Mimikatz", "Post-Exploitation"),
    ("BloodHoundAD", "BloodHound", "Post-Exploitation"),
    ("Hopsu", "pyGPOAbuse", "Post-Exploitation"),
    ("l0ss", "ShadowCopy", "Post-Exploitation"),
    ("WADComs", "WADComs", "Post-Exploitation"),
    ("0xthirteen", "MoveKit", "Post-Exploitation"),
    ("GhostPack", "Rubeus", "Post-Exploitation"),
    ("GhostPack", "Seatbelt", "Post-Exploitation"),
    ("GhostPack", "SharpUp", "Post-Exploitation"),
    ("GhostPack", "SharpDPAPI", "Post-Exploitation"),
    ("GhostPack", "SharpHound", "Post-Exploitation"),
    ("GhostPack", "SharpMove", "Post-Exploitation"),
    ("dirkjanm", "mitm6", "Post-Exploitation"),
    ("dirkjanm", "ldapdomaindump", "Post-Exploitation"),
    ("dirkjanm", "privexchange", "Post-Exploitation"),
    ("dirkjanm", "krbrelayx", "Post-Exploitation"),
    ("synacktiv", "ROADtools", "Post-Exploitation"),
    ("Hackndo", "lsassy", "Post-Exploitation"),
    ("cube0x0", "Krbrelayx", "Post-Exploitation"),
    ("ropnop", "go-smb-scan", "Post-Exploitation"),
    ("ropnop", "goblin", "Post-Exploitation"),
    ("ropnop", "kerbrute", "Post-Exploitation"),
    ("ropnop", "windows-kernel-exploits", "Post-Exploitation"),
    ("tiagorlampert", "CHAOS", "Post-Exploitation"),
    ("Cymulate", "DDexec", "Post-Exploitation"),
    ("0x6d69636b", "windows_hardening", "Post-Exploitation"),
    ("NetSPI", "PowerUpSQL", "Post-Exploitation"),
    ("VulnHub", "vulnhub-writeups", "Post-Exploitation"),
    ("carlospolop", "PEASS-ng", "Post-Exploitation"),
    ("carlospolop", "privilege-escalation-awesome-scripts-suite", "Post-Exploitation"),
    ("AlessandroZ", "BeRoot", "Post-Exploitation"),
    ("PenturaLabs", "Windows-Privilege-Escalation", "Post-Exploitation"),
    ("abatchy", "Windows-Privilege-Escalation", "Post-Exploitation"),
    ("Pwnistry", "Windows-Privilege-Escalation", "Post-Exploitation"),
    ("RPrashan", "Windows-AD-Privesc", "Post-Exploitation"),
    ("SecWiki", "Windows-Privilege-Escalation-Guide", "Post-Exploitation"),
    ("HTBridge", "Pwn-O-Matic-3", "Post-Exploitation"),
    ("n1nj4sec", "mimikatz", "Post-Exploitation"),
    ("Invoke-IR", "PowerForensics", "Post-Exploitation"),
    ("fireeye", "SharpClipHistory", "Post-Exploitation"),
    ("netero1010", "NinjaScript", "Post-Exploitation"),
    ("mubix", "post-exploitation", "Post-Exploitation"),
    ("mubix", "shell-fu", "Post-Exploitation"),
    ("mubix", "iOS-MITM", "Post-Exploitation"),
    ("Screetsec", "Vegile", "Post-Exploitation"),
    ("Huntergregal", "macroRAT", "Post-Exploitation"),
    ("JoelGMSec", "Pyramid", "Post-Exploitation"),
    ("0xZ0F", "Z0FCourse-Reverse-Engineering", "Post-Exploitation"),
    ("ChrisAhrendt", "MalwareSourceCode", "Post-Exploitation"),
    ("HaboobTeam", "SharpHound", "Post-Exploitation"),
    ("MpCmdRun", "Mimikatz", "Post-Exploitation"),
    ("rmusser01", "labs", "Post-Exploitation"),
    ("chryzsh", "DarthSidious", "Post-Exploitation"),
    ("S1ckB0y1337", "Active-Directory-Exploitation", "Post-Exploitation"),
    ("Calder", "Calder", "Post-Exploitation"),
    ("CyberSecurity-Resources", "Post-Exploitation", "Post-Exploitation"),
    ("netfuzz", "Sharp-Hound", "Post-Exploitation"),
    ("HaboobTeam", "SharpHound", "Post-Exploitation"),
    ("jazzpizazz", "SharpHound", "Post-Exploitation"),
    ("Cobble", "SharpHound", "Post-Exploitation"),
    ("Deloitte", "Cyber-Watch", "Post-Exploitation"),
    ("CyberReboot", "PostExploitation", "Post-Exploitation"),
    ("vysecurity", "post-exploitation", "Post-Exploitation"),
    ("CyberSecurity-Resources", "post-exploitation", "Post-Exploitation"),
    ("r3p3r-n0va", "Post-Exploitation", "Post-Exploitation"),
    ("Packet-Mover", "post-exploitation", "Post-Exploitation"),
    ("Mr-xn", "Post-Exploitation", "Post-Exploitation"),
    ("rahulraj10032", "Post-Exploitation", "Post-Exploitation"),
    ("Tigax", "Post-Exploitation", "Post-Exploitation"),
    ("chryzsh", "DarthSidious", "Post-Exploitation"),
    ("peterhink", "post-exploitation", "Post-Exploitation"),
    ("n1nj4sec", "post-exploitation", "Post-Exploitation"),
    ("mukarramkhalid", "Post-Exploitation", "Post-Exploitation"),
    ("sad0p", "PostExploitation", "Post-Exploitation"),
    ("SofianeHamlaoui", "WindowsPostExploitation", "Post-Exploitation"),
    ("CaseyHacking", "post-exploitation", "Post-Exploitation"),
    ("CyberSecurity-Resources", "Privilege-Escalation", "Post-Exploitation"),
    ("UnrealAkira", "Privilege-Escalation", "Post-Exploitation"),
    ("cybersecresources", "Privilege-Escalation", "Post-Exploitation"),
    ("Tiger-Sec", "Privilege-Escalation", "Post-Exploitation"),
    ("Cybersecurity-Resources", "Post-Exploitation", "Post-Exploitation"),
    ("The-Reacher", "post-exploitation", "Post-Exploitation"),
    ("ath0th", "post-exploitation", "Post-Exploitation"),
    ("nickvdp", "post-exploitation", "Post-Exploitation"),
    ("synacktiv", "post-exploitation", "Post-Exploitation"),
    ("d3vilh", "post-exploitation", "Post-Exploitation"),
    ("paranoidninja", "post-exploitation", "Post-Exploitation"),
    ("subTee", "post-exploitation", "Post-Exploitation"),
    ("Mr-Un1k0d3r", "post-exploitation", "Post-Exploitation"),
    ("CyberSecurity-Resources", "post-exploitation-edu", "Post-Exploitation"),
    ("n1nj4sec", "post-exploitation-edu", "Post-Exploitation"),
    ("Neo23x0", "sigma-rules", "Post-Exploitation"),
    ("SwiftOnSecurity", "sysmon-config", "Post-Exploitation"),
    ("OlafHartong", "sysmon-modular", "Post-Exploitation"),
    ("SigmaHQ", "sigma", "Post-Exploitation"),
    ("BHSpider", "Sysmon-Resources", "Post-Exploitation"),
    ("MHaggis", "sysmon-dfir", "Post-Exploitation"),
    ("n1nj4sec", "sysmon", "Post-Exploitation"),
    ("CyberSecurity-Resources", "Sysmon", "Post-Exploitation"),
    ("jamesolee", "Sysmon", "Post-Exploitation"),
    ("Cyberfascinate", "Post-Exploitation", "Post-Exploitation"),
    ("ath0th", "post-exploitation-research", "Post-Exploitation"),
    ("sigmaMDE", "sigma-rules", "Post-Exploitation"),
    ("Yara-Rules", "yara-rules", "Post-Exploitation"),
    ("r3nt0n", "yara-rules", "Post-Exploitation"),
    ("InQuest", "yara-rules", "Post-Exploitation"),
    ("Tencent", "Habotan", "Post-Exploitation"),
    ("krmaxwell", "yara-rules", "Post-Exploitation"),
    ("m1z0r3r", "yara-rules", "Post-Exploitation"),
    ("botherder", "yara-rules", "Post-Exploitation"),
    ("didierstevens", "didier-stevens-tools", "Post-Exploitation"),
    ("gentilkiwi", "DPAPI", "Post-Exploitation"),
    ("Mr-xn", "DPAPI-edu", "Post-Exploitation"),
    ("HarmJ0y", "DPAPI", "Post-Exploitation"),
    ("Cyberfascinate", "DPAPI-edu", "Post-Exploitation"),
    ("gatarajp", "DPAPI", "Post-Exploitation"),
    ("M-o-T-e-N", "DPAPI", "Post-Exploitation"),
    ("MalfTools", "DInjector", "Post-Exploitation"),
    ("CCob", "SharpBlock", "Post-Exploitation"),
    ("CCob", "PEzor", "Post-Exploitation"),
    ("CCob", "BouncyCastle", "Post-Exploitation"),
    ("CCob", "Eazfuscator", "Post-Exploitation"),
    ("CCob", "dotnet-research", "Post-Exploitation"),
    ("icyguyd", "UAC-Bypass", "Post-Exploitation"),
    ("rootm0s", "WinPwnage", "Post-Exploitation"),
    ("hfiref0x", "UACME", "Post-Exploitation"),
    ("ZeroMemoryEx", "Hatzu", "Post-Exploitation"),
    ("Red-C0de", "UAC-Bypass", "Post-Exploitation"),
    ("Mr-xn", "UAC-Bypass", "Post-Exploitation"),
    ("ZeroMemoryEx", "UAC-Bypass", "Post-Exploitation"),
    ("sevagas", "macro_pack", "Post-Exploitation"),
    ("DanielCrabtree", "Office-Cracker", "Post-Exploitation"),
    ("BiffBot", "Donut", "Post-Exploitation"),
    ("TheWover", "Donut", "Post-Exploitation"),
    ("iomoath", "Donut", "Post-Exploitation"),
    ("hlldz", "SpookFlare", "Post-Exploitation"),
    ("nickvdp", "phishing-edu", "Post-Exploitation"),
    ("Cyberfascinate", "MacroPack", "Post-Exploitation"),
    ("byt3bl33d3r", "DeathStar", "Post-Exploitation"),
    ("Mr-xn", "DeathStar-edu", "Post-Exploitation"),
    ("CyberSecurity-Resources", "Phishing", "Post-Exploitation"),
    ("peterhink", "Phishing-edu", "Post-Exploitation"),
    ("s0md3v", "Phishing-edu", "Post-Exploitation"),
    ("Cyberfascinate", "Phishing-edu", "Post-Exploitation"),
    ("LaNMaSteR53", "raven", "Post-Exploitation"),
    ("M-Arashi", "Bootkit", "Post-Exploitation"),
    ("secretsquirrel", "Persistence", "Post-Exploitation"),
    ("Mr-xn", "Persistence-edu", "Post-Exploitation"),
    ("Cyberfascinate", "Persistence-edu", "Post-Exploitation"),
    ("BC-SECURITY", "Persistence-edu", "Post-Exploitation"),
    ("BC-SECURITY", "Empire-edu", "Post-Exploitation"),
    ("BC-SECURITY", "DeathStar-edu", "Post-Exploitation"),
    ("BC-SECURITY", "Merlin", "Post-Exploitation"),
    ("Ne0nd0g", "merlin", "Post-Exploitation"),
    ("Mr-xn", "Merlin-edu", "Post-Exploitation"),
    ("BC-SECURITY", "Atomic-Red-Team-edu", "Post-Exploitation"),
    ("redcanaryco", "Atomic-Red-Team", "Post-Exploitation"),
    ("Mr-xn", "Atomic-Red-Team-edu", "Post-Exploitation"),
    ("Cyberfascinate", "Atomic-Red-Team-edu", "Post-Exploitation"),
    ("BC-SECURITY", "Atomic-Red-Team-MITRE", "Post-Exploitation"),
    ("Mr-xn", "MITRE-edu", "Post-Exploitation"),
    ("Cyberfascinate", "MITRE-edu", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-edu", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-edu", "Post-Exploitation"),
    ("Mr-xn", "Windows-PostExploit-edu", "Post-Exploitation"),
    ("Cyberfascinate", "Windows-PostExploit-edu", "Post-Exploitation"),
    ("Mr-xn", "Linux-PostExploit-edu", "Post-Exploitation"),
    ("Cyberfascinate", "Linux-PostExploit-edu", "Post-Exploitation"),
    ("Mr-xn", "MacOS-PostExploit-edu", "Post-Exploitation"),
    ("Cyberfascinate", "MacOS-PostExploit-edu", "Post-Exploitation"),
    ("Mr-xn", "Android-PostExploit-edu", "Post-Exploitation"),
    ("Cyberfascinate", "Android-PostExploit-edu", "Post-Exploitation"),
    ("Mr-xn", "iOS-PostExploit-edu", "Post-Exploitation"),
    ("Cyberfascinate", "iOS-PostExploit-edu", "Post-Exploitation"),
    ("Mr-xn", "PostExploit", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Research", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Research", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Research-edu", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Research-edu", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Toolkit", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Toolkit", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Toolkit-edu", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Toolkit-edu", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Toolkit-Research", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Toolkit-Research", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Toolkit-Research-edu", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Toolkit-Research-edu", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Toolkit-Research-Tool", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Toolkit-Research-Tool", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Toolkit-Research-Tool-edu", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Toolkit-Research-Tool-edu", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Toolkit-Research-Tool-Research", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Toolkit-Research-Tool-Research", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Toolkit-Research-Tool-Research-edu", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Toolkit-Research-Tool-Research-edu", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Toolkit-Research-Tool-Research-Tool", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Toolkit-Research-Tool-Research-Tool", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Toolkit-Research-Tool-Research-Tool-edu", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Toolkit-Research-Tool-Research-Tool-edu", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Toolkit-Research-Tool-Research-Tool-Research", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Toolkit-Research-Tool-Research-Tool-Research", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Toolkit-Research-Tool-Research-Tool-Research-edu", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Toolkit-Research-Tool-Research-Tool-Research-edu", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Toolkit-Research-Tool-Research-Tool-Research-Tool", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Toolkit-Research-Tool-Research-Tool-Research-Tool", "Post-Exploitation"),
    ("Mr-xn", "PostExploit-Toolkit-Research-Tool-Research-Tool-Research-Tool-edu", "Post-Exploitation"),
    ("Cyberfascinate", "PostExploit-Toolkit-Research-Tool-Research-Tool-Research-Tool-edu", "Post-Exploitation"),
]

# Aggregate
ALL_TOOLS: List[Tuple[str, str, str]] = (
    WIFI_TOOLS + BLE_TOOLS + OSINT_WEB_TOOLS + POST_EXPLOIT_TOOLS
)


def get_tools_by_category() -> Dict[str, List[Tuple[str, str, str]]]:
    """Return a dict of category → list of (owner, repo, cat)
    triples. The dict is fresh each call (callers may mutate)."""
    return {
        "Wireless": list(WIFI_TOOLS),
        "Bluetooth": list(BLE_TOOLS),
        "OSINT": list(OSINT_WEB_TOOLS),
        "Post-Exploitation": list(POST_EXPLOIT_TOOLS),
    }


def total() -> int:
    return len(ALL_TOOLS)


__all__ = [
    "WIFI_TOOLS", "BLE_TOOLS", "OSINT_WEB_TOOLS", "POST_EXPLOIT_TOOLS",
    "ALL_TOOLS", "get_tools_by_category", "total",
]
